blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: http://doc.huangsw.com/issue-template-generater/
    about: The issue which is not created via http://doc.huangsw.com/issue-template-generater/ will be closed immediately.
